### PR TITLE
Fix slow fps when no joysticks

### PR DESCRIPTION
**Pull request by dascandy**
On my system for some reason, SDL reports one joystick. I don't know what it thinks is a joystick, but it also seems to indicate it's not a usable one. The joystick code in OpenSupaplex seems to cause the framerate to drop as a brick if it reprobes a bunch of times per second. Without this patch I get about 2 FPS in-game and in the menu, but 60FPS during transitions. With this patch, it's smooth 60FPS all around.

Let me know if you have something I can test instead of this. This patch makes it so that runtime plugged in joysticks will only work if there's at least one working joystick available at all times.

### CODE REVIEW

**Comment by sergiou87** [comment]
The problem with this patch is that the game will not recognize any game controllers if they're not connected from the beginning. You should be able to enumerate the Joysticks detected by SDL and find which specific device is causing you this problem, and or why is it so slow to check if that joystick is a game controller or not.

I'm sorry but this looks more of an issue in SDL than in OpenSupaplex 😅

**Comment by dascandy** [comment]
Honestly... kinda. I have no idea why it's taking so long, or why it shows a device that it already knows won't work. Will see if I can find this in SDL.

**Comment by dascandy** [comment]
So I learned that SDL differentiates between "Joysticks" - things that can be accessed through the OS Joystick API, and "Game Controllers", joysticks that roughly match a typical actual joystick.

In this case, the code is re-probing the joysticks many times a frame. While I agree that SDL shouldn't be this slow, it seems to be actually using the device for the probe every time, making it really slow to check. Will create a SDL issue & link here.

**Comment by dascandy** [comment]
incidentally, the "game controller" in question is called "ASRock LED Controller". Not too uncommon to have in computers, so more people might be affected.

**Comment by dascandy** [comment]
Checked a few things, the SDL_IsGameController call takes on average 20-30 milliseconds. For a function that looks like a property lookup that's very long. Filing a bug on SDL, since even with checking this only once per frame would make getting 30FPS hard, and it is completely known in SDL whether it needs to be re-checked.

**Comment by dascandy** [comment]
Linked SDL ticket - https://github.com/libsdl-org/SDL/issues/5211

**Comment by dascandy** [comment]
Fixed in latest SDL version (by ignoring the device entirely).

**Comment by sergiou87** [comment]
Yay! That's awesome, thank you!

**Pull request closed without merging**
