### PR TITLE
Add a docker image for RISC OS builds

### PR DESCRIPTION
**Pull request by ccawley2011**
The CI workflows have also been updated, but are disabled for now.

### CODE REVIEW

**Comment by sergiou87** [comment]
As with the NDS PR, happy to upload the Docker image and getting it ready for this 😄

**Comment by sergiou87** [comment]
@ccawley2011 done! https://hub.docker.com/r/sergiou87/riscos-docker-open-supaplex sorry again for making you wait 😳

**Comment by ccawley2011** [comment]
> @ccawley2011 done! https://hub.docker.com/r/sergiou87/riscos-docker-open-supaplex sorry again for making you wait 😳

Thanks, I've updated this PR accordingly.

**Review by sergiou87 — APPROVED** [review]
:shipit:

**Pull request merged**
