### PR TITLE
Add a docker image for Nintendo DS builds

### PR DESCRIPTION
**Pull request by ccawley2011**
The CI workflows have also been updated, but are disabled for now.

### CODE REVIEW

**Comment by sergiou87** [comment]
Thanks for this! Do you need me to create the Docker images and upload them as `sergiou87/nds-docker-open-supaplex:7.2`?

**Comment by ccawley2011** [comment]
> Thanks for this! Do you need me to create the Docker images and upload them as `sergiou87/nds-docker-open-supaplex:7.2`?

Yes please. I'll update this PR to enable the workflow changes once that's done.

**Comment by sergiou87** [comment]
Sorry it took a while @ccawley2011, busy weeks 😅 I just pushed the image as promised: https://hub.docker.com/r/sergiou87/nds-docker-open-supaplex

**Comment by ccawley2011** [comment]
> Sorry it took a while @ccawley2011, busy weeks 😅 I just pushed the image as promised: https://hub.docker.com/r/sergiou87/nds-docker-open-supaplex

Thanks, I've updated this PR accordingly.

**Review by sergiou87 — APPROVED** [review]
:shipit:

**Pull request merged**
