### PR TITLE
Migrate Wii port to SDL2

### PR DESCRIPTION
**Pull request by mardy**
I didn't actually try the CI, just a local build. It seems to work fine :-)

### CODE REVIEW

**Comment by sergiou87** [comment]
CI doesn't work because it's based on a Docker image that doesn't contain SDL2… that would require to update https://github.com/sergiou87/open-supaplex/blob/master/ci/Dockerfile-wii with the new dependencies, then I like to push a new image to my Docker account and update [this line](https://github.com/sergiou87/open-supaplex/blob/53e45e9267593b9e53446267edf1e5ed06a40c24/.github/workflows/build-release.yml#L106) with the new image.

**Comment by sergiou87** [comment]
Btw does upgrading to SDL2 bring any improvements to the Wii version?

**Comment by mardy** [comment]
> CI doesn't work because it's based on a Docker image that doesn't contain SDL2… that would require to update https://github.com/sergiou87/open-supaplex/blob/master/ci/Dockerfile-wii with the new dependencies

That is done, but I didn't actually build the image :-)

> Btw does upgrading to SDL2 bring any improvements to the Wii version?

Honestly, I'm not aware of any. If you know of some bugs that were there in the SDL1 version, I can check and see if they are gone.

**Comment by sergiou87** [comment]
> Honestly, I'm not aware of any. If you know of some bugs that were there in the SDL1 version, I can check and see if they are gone.

My question then is… why upgrading it then? I tested the existing version with SDL1 on Wii back in the day and it worked well, so I'd be afraid of breaking anything with changes if they don't add anything 😳

**Comment by mardy** [comment]
> My question then is… why upgrading it then?

I submitted it just in case one day you'll have all platforms on SDL2, so taht you can drop SDL1. Feel free to do what you want with this :-)

**Comment by sergiou87** [comment]
Since I don't have bandwidth to work on this I will close it. If needed in the future it should be easy to reopen. Sorry and thank you for your contribution 💖

**Pull request closed without merging**
