### PR TITLE
Use sdl key lookup

### PR DESCRIPTION
**Pull request by dascandy**
This should make it use the active keyboard layout so players can type their name on Colemak, Dvorak, German, Belgian and other layouts too. 

I only have QWERTY so have not tested that it fixes their problem, but the docs say it should, and it does not break QWERTY (did check that).

### CODE REVIEW

**Comment by dascandy** [comment]
Ready to merge, tested by @DarthGandalf & myself on two different keyboard layouts.

**Comment by sergiou87** [comment]
@dascandy I'm afraid this branch has 2 commits that are not relevant, please consider this:
1. Remove the irrelevant commits and leave the only one about SDL key lookup
2. Rebase your branch on top of the latest `master` from my repo

After that, everything should be ok for merging 😄 

Thank you!! 🙇‍♂️

**Comment by PeterBindels-TomTom** [comment]
Ah sorry, forgot about this. Should be good now.

**Comment by dascandy** [comment]
Sorry, forgot about this. This should work now.

**Review by sergiou87 — APPROVED** [review]
Works as expected, thank you!!!

**Pull request merged**
